# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

best_subset_selection <- function(X_r, y_r, max_variables = -1L, top_n = 10L, metric = "accuracy", use_cv = FALSE, cv_folds = 5L, cv_repeats = 1L, cv_seed = -1L, include_intercept = TRUE, max_iterations = 100L, tolerance = 1e-6) {
    .Call(`_bestSelectR_best_subset_selection`, X_r, y_r, max_variables, top_n, metric, use_cv, cv_folds, cv_repeats, cv_seed, include_intercept, max_iterations, tolerance)
}

predict_best_subset <- function(model_info, X_new, type = "class") {
    .Call(`_bestSelectR_predict_best_subset`, model_info, X_new, type)
}

